{ config, pkgs, lib, inputs, myLib, ... }:

let
  cfg = config.myHomeModules.system.hyprland;

  homeDirectory = config.home.homeDirectory;

  rust-core = inputs.rust-utils.packages.${pkgs.system}.default;

  awww-random = myLib.mkWrappedBinary {
    inherit pkgs;
    binPath = lib.getExe' rust-core "awww-random";
    outName = "awww-random";
    runtimePkgs = with pkgs; [ awww ];
  };
in {
  config = lib.mkIf cfg.enable {
    wayland.windowManager.hyprland = {
      enable = true;

      configType = "lua";

      extraConfig = ''
        require('hyprland.init')
      '';
};

    home.file = {
      ".config/hypr/hyprland/" = {
        source = ./lua;
        recursive = true;
      };

      ".config/hypr/hyprland/host_vars.lua".text = ''
        -- This file is auto-generated by Nix! Do not edit.
        return {
           home_path = "${homeDirectory}/",
           awww_random_path = "${awww-random}/",
           wallpapers_path = "${cfg.wallpapers_path}/",
           nw_applet_path = "${pkgs.networkmanagerapplet}/",
           numlock_by_default = ${lib.boolToString cfg.numlock_by_default},
        }
      '';
    };
  };
}
