{ config, pkgs, lib, ... }:

let
  cfg = config.myHomeModules.system.hyprland;

  homeDirectory = config.home.homeDirectory;

  # TODO: Update random script
  # TODO: Conditional logic to handle null wallpapers path
  awww-random = pkgs.writeShellScriptBin "awww-random" ''
    sleep 1
    if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
      echo "Usage:
      $0 <path/to/wallpapers/folder>"
      exit 1
    fi

    # Edit below to control the images transition
    export AWWW_TRANSITION_FPS=60
    export AWWW_TRANSITION_STEP=2

    # This controls (in seconds) when to switch to the next image
    INTERVAL=300

    while true; do
      find "$1" -type f \
        | while read -r img; do
          echo "$((RANDOM % 1000)):$img"
        done \
        | sort -n | cut -d':' -f2- \
        | while read -r img; do
          awww img "$img"
          sleep $INTERVAL
        done
    done
  '';
in {
  config = lib.mkIf cfg.enable {
    home.file = {
      ".config/hypr/" = {
        source = ./lua;
        recursive = true;
      };

      ".config/hypr/host_vars.lua".text = ''
        -- This file is auto-generated by Nix! Do not edit.
        return {
           home_path = "${homeDirectory}/",
           awww_random_path = "${awww-random}/",
           wallpapers_path = "${cfg.wallpapers_path}/",
           nw_applet_path = "${pkgs.networkmanagerapplet}/",
           numlock_by_default = ${lib.boolToString cfg.numlock_by_default},
        }
      '';
    };
  };
}
