# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."cryptbtrfs".device = "/dev/disk/by-uuid/357b7952-34a0-4671-8c44-2dd7dfb428d8";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=log" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=swap" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=srv" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=tmp" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=var_tmp" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/lib/portables" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=portables" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/085f5c11-2189-4740-a4ff-2214fd8a3d60";
      fsType = "btrfs";
      options = [ "subvol=machines" "compress-force=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0268-D56F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/.swapvol/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
