# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."cryptbtrfs".device = "/dev/disk/by-uuid/278ed293-c19a-413f-8ba8-a927d88a2a20";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=swap" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=srv" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/lib/portables" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=portables" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/lib/machines" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=machines" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=tmp" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/0f30ab1d-41f2-4035-ad36-b6747ef9bc82";
      fsType = "btrfs";
      options = [ "subvol=var_tmp" "compress=zstd:1" "noautodefrag" "noatime" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/74CF-D32A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Shared partition for dual booting
  fileSystems."/mnt/Shared" =
    { device = "/dev/disk/by-uuid/F856E51156E4D184";
      fsType = "ntfs";
    };

  swapDevices = [ { device = "/.swapvol/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
